name: pocketcoach
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  audio_session: ^0.2.1
  audioplayers: ^6.4.0
  cached_network_image: ^3.4.1
  camera: ^0.11.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  easy_audience_network: ^0.0.7
  exif: ^3.3.0
  file_picker: ^10.1.2
  firebase_analytics: ^11.4.5
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_database: ^11.3.5
  firebase_messaging: ^15.2.5
  flutter_bloc: ^9.1.0
  flutter_branch_sdk: ^8.4.1
  flutter_email_sender: ^7.0.0
  flutter_facebook_auth: ^7.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_local_notifications: ^19.1.0
  flutter_localization: ^0.3.2
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  flutter_slidable: ^4.0.0
  flutter_stripe: ^11.5.0
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.1
  google_sign_in: ^6.3.0
  google_mobile_ads: ^6.0.0
  googleapis_auth: ^2.0.0
  http: ^1.3.0
  image: ^4.5.4
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.1
  intl: ^0.19.0
  location: ^8.0.0
  lottie: ^3.3.1
  mailer: ^6.4.1
  open_file: ^3.5.10
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0
  popover: ^0.3.1
  provider: ^6.1.4
  razorpay_flutter: ^1.4.0
  screen_state: ^4.1.1
  sensors_plus: ^6.1.1
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  video_player: ^2.9.5
  volume_controller: ^3.3.3
  webview_flutter: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/img_1.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/UI/
    - assets/icon/
    - assets/icon2/
    - assets/lang/
